# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-16 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='email_address',
            new_name='email',
        ),
    ]
